# Combined Workflow
#
# Handles both PR reviews and interactive @takt mentions.
# Single workflow for all TAKT Action features.

name: TAKT
on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  takt:
    if: >
      github.event_name == 'pull_request' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@takt'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nrslib/takt-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Specify model (opus, sonnet, haiku)
          # model: sonnet
          # For Codex provider:
          # provider: codex
          # openai_api_key: ${{ secrets.OPENAI_API_KEY }}
